CREATE SCHEMA `BANK_DB` ;

CREATE TABLE `BANK_DB`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ФИО` VARCHAR(50) NOT NULL,
  `Пасспорт(серия/номер)` VARCHAR(10) NOT NULL,
  `Телефон` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=1
;
  
CREATE TABLE `BANK_DB`.`contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Клиент` INT NOT NULL,
  `Менеджер` INT NOT NULL,
  `Дата_Создания` DATE NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=1000001
;

CREATE TABLE `BANK_DB`.`manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ФИО` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=101
;

CREATE TABLE `BANK_DB`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Баланс` DECIMAL(11,2) NOT NULL,
  `idДоговора` INT(11) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=10001
;

CREATE TABLE `BANK_DB`.`operation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Сумма` DECIMAL(11,2) NOT NULL,
  `Операция` VARCHAR(20) NOT NULL,
  `idСчета` INT NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=1
;