
CREATE SCHEMA IF NOT EXISTS BANK_DB ;

CREATE TABLE client (
   id INT NOT NULL AUTO_INCREMENT,
   Full_Name VARCHAR(50) NOT NULL,
   Passport VARCHAR(11) NOT NULL,
   Phone_Number VARCHAR(20) NOT NULL,
   PRIMARY KEY (id)
)
AUTO_INCREMENT=1;

  
CREATE TABLE contract (
   id INT NOT NULL AUTO_INCREMENT,
   Client INT NOT NULL,
   Manager INT NOT NULL,
   Date_Of_Contract DATE NOT NULL,
   PRIMARY KEY (id)
)
AUTO_INCREMENT=1000001;


CREATE TABLE manager (
   id INT NOT NULL AUTO_INCREMENT,
   Full_Name VARCHAR(50) NOT NULL,
   PRIMARY KEY (id)
)
AUTO_INCREMENT=101;

CREATE TABLE account (
   id INT NOT NULL AUTO_INCREMENT,
   Ballance DECIMAL(11,2) NOT NULL,
   Contract INT(11) NOT NULL,
   PRIMARY KEY (id)
)
AUTO_INCREMENT=10001;

CREATE TABLE operation_type (
   id INT NOT NULL AUTO_INCREMENT,
   Amount DECIMAL(11,2) NOT NULL,
   Operation_Type VARCHAR(20) NOT NULL,
   Account INT NOT NULL,
  PRIMARY KEY (id)
)
AUTO_INCREMENT=1;